/**
 *
 *    ___                             _    ____ ___
 *   / _ \ _   _  ___ _ __ _   _     / \  |  _ \_ _|
 *  | | | | | | |/ _ \ '__| | | |   / _ \ | |_) | |
 *  | |_| | |_| |  __/ |  | |_| |  / ___ \|  __/| |
 *   \__\_\__,_|\___|_|   \__, | /_/   \_\_|  |___|
 *                         |___/
 *
 * This file was generated by the Query API Type Generator.
 * Please do not edit this file manually. Changes made in this file might get lost.
 * To update it, run the 'craft query-api/typescript/generate-types' command.
 */

// --- hardTypes ---
export type CraftDateTime = {
  date: string
  timezone: string
  timezone_type: number
}

export type CraftColor = {
  hex: string
  rgb: string
  hsl: string
}

export type CraftCountry = {
  name: string
  countryCode: string
  threeLetterCode: string
  locale: string
  currencyCode: string
  timezones: string[]
}

export type CraftMoney = {
  amount: string
  currency: string
}

export type CraftLinkTarget = '_blank' | '_self'

export type CraftLink = {
  elementType: string
  url: string
  label: string
  target: CraftLinkTarget
  rel: string
  urlSuffix: string
  class: string
  id: string
  ariaLabel: string
  download: boolean
  downloadFile: string
}

export type CraftJson = object | object[]

export type CraftAssetFocalPoint = {
  x: number
  y: number
}

export type CraftAssetMeta = {
  id: number
  filename: string
  kind: string
  size: string
  mimeType: string
  extension: string
  cpEditUrl: string
  volumeId: number
}

export type CraftAddressMeta = {
  id: number
}

export type CraftUserStatus =
  | 'inactive'
  | 'active'
  | 'pending'
  | 'credentialed'
  | 'suspended'
  | 'locked'

export type CraftUserMeta = {
  id: number
  status: CraftUserStatus
  cpEditUrl: string
}

export type CraftEntryRelation = {
  title: string
  slug: string
  url: string
  id: number
}

export type CraftEntryStatus = 'live' | 'pending' | 'expired' | 'disabled'

export type CraftEntryMeta = {
  id: number
  entryType: string
  sectionId: number
  siteId: number
  url: string
  slug: string
  uri: string
  fullUri: string
  status: CraftEntryStatus
  cpEditUrl: string
}

export interface CraftPageBase {
  metadata: CraftEntryMeta
  sectionHandle: string
  title: string
}

export type CraftTagMeta = {
  id: number
}

export type CraftTag = {
  metadata: CraftTagMeta
  title: string
  slug: string
}

// --- addresses ---
export type CraftAddress = {
  metadata: CraftAddressMeta
  title: string
  addressLine1: string
  addressLine2: string
  addressLine3: string
  countryCode: string
  locality: string
  postalCode: string
}

// --- assets ---
export type CraftAssetRatio = {
  auto: string
  '1:1': string
  '3:2': string
}

export type CraftVolumeImages = {
  metadata: CraftAssetMeta
  height: number
  width: number
  focalPoint: CraftAssetFocalPoint
  url: string
  title: string
  srcSets: CraftAssetRatio
  alt: string | null
}

export type CraftAsset = CraftVolumeImages

// --- entryTypes ---
export interface CraftEntryTypeHome {
  title: string
  translatablePlainText: string | null
  richText: string | null
  image: CraftAsset | null
  contentBuilder:
    | (
        | CraftEntryTypeHeadline
        | CraftEntryTypeText
        | CraftEntryTypeImageAndText
        | CraftEntryTypeImage
      )[]
    | null
}

export interface CraftEntryTypeNews {
  title: string
  translatablePlainText: string | null
  richText: string | null
  image: CraftAsset | null
  contentBuilder:
    | (
        | CraftEntryTypeHeadline
        | CraftEntryTypeText
        | CraftEntryTypeImageAndText
        | CraftEntryTypeImage
      )[]
    | null
  selectAuthor: CraftUser | null
}

export interface CraftEntryTypeHeadline {
  title: string
  selectHeadlineTag: CraftOptionSelectHeadlineTag
}

export interface CraftEntryTypeImageAndText {
  title: string
  selectHeadlineTag: CraftOptionSelectHeadlineTag
  richText: string | null
  image: CraftAsset
}

export interface CraftEntryTypeText {
  richText: string | null
}

export interface CraftEntryTypeImage {
  image: CraftAsset | null
}

export interface CraftPageHome extends CraftEntryTypeHome {
  metadata: CraftEntryMeta
  title: string
  sectionHandle: string
}

export interface CraftPageNews extends CraftEntryTypeNews {
  metadata: CraftEntryMeta
  title: string
  sectionHandle: string
}

// --- users ---
export type CraftUser = {
  metadata: CraftUserMeta
  username: string | null
  fullName: string | null
  photo: CraftAsset | null
  email: string | null
}

// --- categories ---

// --- tables ---

// --- options ---
export type CraftOptionValueSelectHeadlineTag = 'h2' | 'h3' | 'h4' | 'h5'

export type CraftOptionSelectHeadlineTag = {
  label: string
  selected: boolean
  valid: boolean
  icon: string | null
  color: string | null
  value: CraftOptionValueSelectHeadlineTag
}

// --- contentBlocks ---
