color: null
description: null
fieldLayouts:
  66ccc7d1-468c-4af9-a8ed-0aa1088c5382:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-12T09:35:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a0aeee7d-14a9-44d9-a1a6-07e8518657c0 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2966306-abe9-4cd0-a63f-1cc76dfd8547
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 512fd508-195c-4ebd-a2cf-bee822943006
        userCondition: null
handle: blockImage
hasTitleField: false
icon: image-landscape
name: 'Block: Image'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
