color: null
description: null
fieldLayouts:
  c2f99198-d6ca-4d3c-8b41-808c941eb6a9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-12T09:26:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b510aee4-7050-4bfe-9d65-7ac1cfcc386c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-12T09:29:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b31aa533-16c8-44d2-8e9f-ffe300c2e7a6 # Select Headline Tag
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18d710b6-1115-495c-bbd2-fadc532253d8
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 77e62c77-2070-47fe-8cd5-0e4816faf2ec
        userCondition: null
handle: headline
hasTitleField: true
icon: h1
name: Headline
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
