color: null
description: null
fieldLayouts:
  c2fc8bab-a5f7-4813-bc13-9a6188a19753:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-12T09:28:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4768b0f-9792-4463-8694-1e0239204062
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-12T09:33:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b31aa533-16c8-44d2-8e9f-ffe300c2e7a6 # Select Headline Tag
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50e7623b-e945-4db4-96ba-1f93bfdf0e50
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-12T09:33:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cfa3a69d-c697-4f3f-98e5-4a898f71797e # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c94d65a-180c-4670-a2cd-e3d5b0fcdcab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-12T09:33:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a0aeee7d-14a9-44d9-a1a6-07e8518657c0 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8aa48013-3ad2-4a42-9230-855839cd44a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ae992f8-80f7-48ae-9477-7c3c5638ea0b
        userCondition: null
handle: imageAndText
hasTitleField: true
icon: image-polaroid
name: 'Image and Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: language
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
