name: Scheduled Link Check on Multiple Branches 🔗

on:
  schedule:
    - cron: '0 2 * * 0'

  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        branch: [main, examples/next, examples/react-vite, examples/vue, examples/nuxt] 

    steps:
      - name: Checkout code from ${{ matrix.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          args: --verbose --no-progress --exclude http://localhost:3000 './**/*.md' './**/*.html' './**/*.rst'

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue